In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

from pathlib import Path

# Set your local project path
local_path = "C:\\Users\\naing\\MultiVacSim"

# Check if the folder exists
if Path(local_path).exists():
    print("Local folder found at:", local_path)
else:
    print("Local folder not found. Please check the path.")

Local folder found at: C:\Users\naing\MultiVacSim

In [2]:
import psutil
import os
def get_memory_usage():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    ram_usage_mb = mem_info.rss / (1024 * 1024)  # Convert bytes to MB
    print(f"🔹 Current RAM Usage: {ram_usage_mb:.2f} MB")

In [3]:
# !ls "/content/drive/My Drive/"

In [4]:
# !ls "/content/drive/My Drive/Spring25_Research/data/covid"

In [5]:
# import pandas as pd

# file_path = "/content/drive/My Drive/Spring25_Research/Data/Covid/Monthly_COVID-19_Death_Rates_per_100_000_Population_by_Age_Group__Race_and_Ethnicity__Sex__and_Region_with_Double_Stratification_20250220.csv"  # Update this path
# df = pd.read_csv(file_path)
# df.head()  # Display the first 5 rows

In [6]:
import pandas as pd
import glob

# folder_path = "/content/drive/My Drive/Spring25_Research/data/covid/"
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\covid\\"

csv_files = glob.glob(folder_path + "*.csv")

for file in csv_files:
    try:
        print(f"✅ Successfully loaded: {file}")
        df = pd.read_csv(file, encoding="utf-8", engine="python")
    except Exception as e:
        print(f"❌ Error loading: {file}")
        print(f"🔴 Error Message: {e}")

✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_COVID-19_Death_Rates_per_100_000_Population_by_Age_Group__Race_and_Ethnicity__Sex__and_Region_with_Double_Stratification_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Children_6_Months_17_Years_Who_Received__1_Influenza_Vaccination_Doses__by_Influenza_Season__Age_Group__and_Jurisdiction__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses_and_Comparison_between_2024-25_and_2023-24_Seasons__by_Age_Group_and_Jurisdiction__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses__by_Age_Group__and_Jurisdiction__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Who_Received__1_Influenza_Vaccination_Doses_and_Comparison_Between_2024-25_and_Two_Previous_Seasons__by_Jurisdiction__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Pan-Respiratory_Virus_Emergency_Department_Network_Data_2023-24_National.csv
❌ Error loading: C:\Users\naing\MultiVacSim\data\covid\Pan-Respiratory_Virus_Emergency_Department_Network_Data_2023-24_National.csv
🔴 Error Message: ',' expected after '"'
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Rates_of_Laboratory-Confirmed_RSV__COVID-19__and_Flu_Hospitalizations_from_the_RESP-NET_Surveillance_Systems_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Total_COVID-19_Deaths_since_January_1__2020_by_Age_Group__Race_Ethnicity__and_Sex_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\united_states_covid19_deaths_ed_visits_and_positivity_by_state.csv
❌ Error loading: C:\Users\naing\MultiVacSim\data\covid\united_states_covid19_deaths_ed_visits_and_positivity_by_state.csv
🔴 Error Message: Expected 1 fields in line 3, saw 18
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_COVID-19_Vaccination_Coverage__by_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Doses__in_Millions__of_Influenza_Vaccines_Distributed_by_Season__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_COVID-19_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Season_and_Age_Group__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_Influenza_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Flu_Season_and_Age_Group__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Influenza_Vaccination_Coverage__by_Flu_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years__United_States__Data_Source__Centers_for_Medicare___Medicaid_Services_Ch.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_and_Comparison_Between_2023-24_and_2024-25_by_Jurisdiction_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_by_Selected_Demographics_and_by_Season__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Hospital_Respiratory_Data__HRD__Metrics_by_Jurisdiction__National_Healthcare_Safety_Network__NHSN__20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Parental_Intent_for_Vaccination_and_Cumulative_Percentage_of_Children_6_Months_-17_Years_Who_are_Up_to_date_with_the_COVID-19_Vaccines_by_Season__United_States_20250220.csv
✅ Successfully loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Rates_of_Laboratory-Confirmed_COVID-19_Hospitalizations_from_the_COVID-NET_Surveillance_System_20250220.csv

In [7]:
import pandas as pd
import glob

# Define the folder path where all CSV files are stored
# folder_path = "/content/drive/My Drive/Spring25_Research/data/covid/"
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\covid\\"

# Get all CSV files in the folder
csv_files = glob.glob(folder_path + "*.csv")

# Store file details
file_info = {}

for file in csv_files:
    try:
        df = pd.read_csv(file, encoding="utf-8", engine="python")
        print(f"✅ Loaded: {file}")

        # Store file details
        file_info[file] = {
            "Columns": list(df.columns),
            "Rows": len(df),
            "Date Column Exists": any("date" in col.lower() for col in df.columns),
            "State Column Exists": any("state" in col.lower() for col in df.columns),
            "Age Group Exists": any("age" in col.lower() for col in df.columns),
            "Vaccination Data": any("vaccine" in col.lower() for col in df.columns),
            "Hospitalization Data": any("hospital" in col.lower() for col in df.columns),
            "Death Data": any("death" in col.lower() for col in df.columns),
        }

    except Exception as e:
        print(f"❌ Error loading: {file} - {e}")

# Convert file details into a DataFrame for easy review
file_overview_df = pd.DataFrame.from_dict(file_info, orient="index")

# Save this overview for reference
file_overview_df.to_csv("C:\\Users\\naing\\MultiVacSim\\data\\file_overview.csv")

# Display the overview
file_overview_df

✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_COVID-19_Death_Rates_per_100_000_Population_by_Age_Group__Race_and_Ethnicity__Sex__and_Region_with_Double_Stratification_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Children_6_Months_17_Years_Who_Received__1_Influenza_Vaccination_Doses__by_Influenza_Season__Age_Group__and_Jurisdiction__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses_and_Comparison_between_2024-25_and_2023-24_Seasons__by_Age_Group_and_Jurisdiction__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses__by_Age_Group__and_Jurisdiction__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Who_Received__1_Influenza_Vaccination_Doses_and_Comparison_Between_2024-25_and_Two_Previous_Seasons__by_Jurisdiction__United_States_20250220.csv
❌ Error loading: C:\Users\naing\MultiVacSim\data\covid\Pan-Respiratory_Virus_Emergency_Department_Network_Data_2023-24_National.csv - ',' expected after '"'
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Rates_of_Laboratory-Confirmed_RSV__COVID-19__and_Flu_Hospitalizations_from_the_RESP-NET_Surveillance_Systems_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Total_COVID-19_Deaths_since_January_1__2020_by_Age_Group__Race_Ethnicity__and_Sex_20250220.csv
❌ Error loading: C:\Users\naing\MultiVacSim\data\covid\united_states_covid19_deaths_ed_visits_and_positivity_by_state.csv - Expected 1 fields in line 3, saw 18
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_COVID-19_Vaccination_Coverage__by_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Doses__in_Millions__of_Influenza_Vaccines_Distributed_by_Season__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_COVID-19_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Season_and_Age_Group__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_Influenza_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Flu_Season_and_Age_Group__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Influenza_Vaccination_Coverage__by_Flu_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years__United_States__Data_Source__Centers_for_Medicare___Medicaid_Services_Ch.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_and_Comparison_Between_2023-24_and_2024-25_by_Jurisdiction_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_by_Selected_Demographics_and_by_Season__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Hospital_Respiratory_Data__HRD__Metrics_by_Jurisdiction__National_Healthcare_Safety_Network__NHSN__20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Parental_Intent_for_Vaccination_and_Cumulative_Percentage_of_Children_6_Months_-17_Years_Who_are_Up_to_date_with_the_COVID-19_Vaccines_by_Season__United_States_20250220.csv
✅ Loaded: C:\Users\naing\MultiVacSim\data\covid\Weekly_Rates_of_Laboratory-Confirmed_COVID-19_Hospitalizations_from_the_COVID-NET_Surveillance_System_20250220.csv

,Columns,Rows,Date Column Exists,State Column Exists,Age Group Exists,Vaccination Data,Hospitalization Data,Death Data
C:\Users\naing\MultiVacSim\data\covid\Monthly_COVID-19_Death_Rates_per_100_000_Population_by_Age_Group__Race_and_Ethnicity__Sex__and_Region_with_Double_Stratification_20250220.csv,"[data_as_of, jurisdiction_residence, data_peri...",84546,False,False,False,False,False,True
C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Children_6_Months_17_Years_Who_Received__1_Influenza_Vaccination_Doses__by_Influenza_Season__Age_Group__and_Jurisdiction__United_States_20250220.csv,"[Current Season, Month, Numerator, Population,...",21483,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses_and_Comparison_between_2024-25_and_2023-24_Seasons__by_Age_Group_and_Jurisdiction__United_States_20250220.csv,"[Current_season, Month, Previous_covid_Season,...",4774,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses__by_Age_Group__and_Jurisdiction__United_States_20250220.csv,"[current_season, Month, Numerator, Population,...",13035,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Monthly_Cumulative_Number_and_Percent_of_Who_Received__1_Influenza_Vaccination_Doses_and_Comparison_Between_2024-25_and_Two_Previous_Seasons__by_Jurisdiction__United_States_20250220.csv,"[Current_season, Month, Previous_flu_Season, J...",9702,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Rates_of_Laboratory-Confirmed_RSV__COVID-19__and_Flu_Hospitalizations_from_the_RESP-NET_Surveillance_Systems_20250220.csv,"[Surveillance Network, Season, MMWR Year, MMWR...",46977,True,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Total_COVID-19_Deaths_since_January_1__2020_by_Age_Group__Race_Ethnicity__and_Sex_20250220.csv,"[data_as_of, data_period_end, demographic, pop...",17,False,False,False,False,False,True
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_COVID-19_Vaccination_Coverage__by_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years_20250220.csv,"[Week Ending, COVID-19_Season, Estimate, MMWR_...",384,True,False,False,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Doses__in_Millions__of_Influenza_Vaccines_Distributed_by_Season__United_States_20250220.csv,"[Influenza_Season, Start_Date, End_Date, Repor...",221,True,False,False,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_COVID-19_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Season_and_Age_Group__United_States_20250220.csv,"[COVID-19_Season, Week_ID, Current_Season_Week...",1449,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Estimated_Number_of_Influenza_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Flu_Season_and_Age_Group__United_States_20250220.csv,"[Cumulative_Doses, Influenza_Season, Setting, ...",4023,False,False,True,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Influenza_Vaccination_Coverage__by_Flu_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years__United_States__Data_Source__Centers_for_Medicare___Medicaid_Services_Ch.csv,"[Week Ending, Influenza_Season, Estimate, MMWR...",1398,True,False,False,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_and_Comparison_Between_2023-24_and_2024-25_by_Jurisdiction_20250220.csv,"[vaccine, geographic_level, geographic_name, d...",1748,False,False,False,True,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_by_Selected_Demographics_and_by_Season__United_States_20250220.csv,"[comparison_type, week_ending, current_season_...",2426,False,False,False,False,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Hospital_Respiratory_Data__HRD__Metrics_by_Jurisdiction__National_Healthcare_Safety_Network__NHSN__20250220.csv,"[Week Ending Date, Geographic aggregation, Num...",15812,True,False,True,False,True,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Parental_Intent_for_Vaccination_and_Cumulative_Percentage_of_Children_6_Months_-17_Years_Who_are_Up_to_date_with_the_COVID-19_Vaccines_by_Season__United_States_20250220.csv,"[Vaccine, Geographic Level, Geographic Name, D...",27515,False,False,False,True,False,False
C:\Users\naing\MultiVacSim\data\covid\Weekly_Rates_of_Laboratory-Confirmed_COVID-19_Hospitalizations_from_the_COVID-NET_Surveillance_System_20250220.csv,"[State, Season, _WeekendDate, AgeCategory_Lege...",165943,True,True,True,False,False,False

In [8]:
import pandas as pd

# folder_path = "/content/drive/My Drive/Spring25_Research/data/covid/"
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\covid\\"

# Load datasets
vaccination_df = pd.read_csv(folder_path + "Weekly_Cumulative_Estimated_Number_of_COVID-19_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Season_and_Age_Group__United_States_20250220.csv")
hospitalization_df = pd.read_csv(folder_path + "Weekly_Rates_of_Laboratory-Confirmed_COVID-19_Hospitalizations_from_the_COVID-NET_Surveillance_System_20250220.csv")
mortality_df = pd.read_csv(folder_path + "Total_COVID-19_Deaths_since_January_1__2020_by_Age_Group__Race_Ethnicity__and_Sex_20250220.csv")
trend_df = pd.read_csv(folder_path + "Weekly_Parental_Intent_for_Vaccination_and_Cumulative_Percentage_of_Children_6_Months_-17_Years_Who_are_Up_to_date_with_the_COVID-19_Vaccines_by_Season__United_States_20250220.csv")

# Save merged datasets
# vaccination_df.to_csv("/content/drive/My Drive/Spring25_Research/data/processed/covid_vaccination_data.csv", index=False)
# hospitalization_df.to_csv("/content/drive/My Drive/Spring25_Research/data/processed/hospitalization_data.csv", index=False)
# mortality_df.to_csv("/content/drive/My Drive/Spring25_Research/data/processed/mortality_data.csv", index=False)
# trend_df.to_csv("/content/drive/My Drive/Spring25_Research/data/processed/trend_data.csv", index=False)

vaccination_df.to_csv("C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_vaccination_data.csv", index=False)
hospitalization_df.to_csv("C:\\Users\\naing\\MultiVacSim\\data\\processed/hospitalization_data.csv", index=False)
mortality_df.to_csv("C:\\Users\\naing\\MultiVacSim\\data\\processed\\mortality_data.csv", index=False)
trend_df.to_csv("C:\\Users\\naing\\MultiVacSim\\data\\processed\\trend_data.csv", index=False)

print("✅ Merged structured datasets saved successfully!")

✅ Merged structured datasets saved successfully!

In [9]:
import pandas as pd
import glob

# folder_path = "/content/drive/My Drive/Spring25_Research/data/covid/"
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\covid\\"

# 🏥 Hospitalization Data (Merge multiple hospitalization-related files)
hospitalization_files = [
    "Weekly_Rates_of_Laboratory-Confirmed_COVID-19_Hospitalizations_from_the_COVID-NET_Surveillance_System_20250220.csv",
    "Weekly_Hospital_Respiratory_Data__HRD__Metrics_by_Jurisdiction__National_Healthcare_Safety_Network__NHSN__20250220.csv",
    "Rates_of_Laboratory-Confirmed_RSV__COVID-19__and_Flu_Hospitalizations_from_the_RESP-NET_Surveillance_Systems_20250220.csv",
    # "united_states_covid19_deaths_ed_visits_and_positivity_by_state.csv"
]
hospitalization_dfs = [pd.read_csv(folder_path + f, low_memory=False) for f in hospitalization_files]
hospitalization_df = pd.concat(hospitalization_dfs, ignore_index=True)

# 💉 Vaccination Data (Merge multiple vaccine-related files)
vaccination_files = [
    "Weekly_Cumulative_Estimated_Number_of_COVID-19_Vaccinations_Administered_in_Pharmacies_and_Physician_Medical_Offices__Adults_18_years_and_older__by_Season_and_Age_Group__United_States_20250220.csv",
    "Monthly_Cumulative_Number_and_Percent_of_Persons_Who_Received_1__2024-25_COVID-19_Vaccination_Doses__by_Age_Group__and_Jurisdiction__United_States_20250220.csv",
    "Weekly_Cumulative_COVID-19_Vaccination_Coverage__by_Season_and_Race_and_Ethnicity__Medicare_Fee-For-Service_Beneficiaries_aged__65_years_20250220.csv",
    "Weekly_Cumulative_Percentage_of_Children_Ages_6_Months_-17_Years_Who_Are_Up_to_date_with_COVID-19_Vaccines_by_Selected_Demographics_and_by_Season__United_States_20250220.csv"
]
vaccination_dfs = [pd.read_csv(folder_path + f, low_memory=False) for f in vaccination_files]
vaccination_df = pd.concat(vaccination_dfs, ignore_index=True)

# ☠️ Mortality Data (Merge death-related files)
mortality_files = [
    "Total_COVID-19_Deaths_since_January_1__2020_by_Age_Group__Race_Ethnicity__and_Sex_20250220.csv",
    "Monthly_COVID-19_Death_Rates_per_100_000_Population_by_Age_Group__Race_and_Ethnicity__Sex__and_Region_with_Double_Stratification_20250220.csv",
    # "Data_Period_Death_Counts_and_Mortality_Rates_by_State.csv"
]
mortality_dfs = [pd.read_csv(folder_path + f, low_memory=False) for f in mortality_files]
mortality_df = pd.concat(mortality_dfs, ignore_index=True)

# 📊 Trend Data (Merge seasonal vaccination trends)
trend_files = [
    "Weekly_Parental_Intent_for_Vaccination_and_Cumulative_Percentage_of_Children_6_Months_-17_Years_Who_are_Up_to_date_with_the_COVID-19_Vaccines_by_Season__United_States_20250220.csv",
    "Weekly_Cumulative_Doses__in_Millions__of_Influenza_Vaccines_Distributed_by_Season__United_States_20250220.csv",
    "Weekly_Hospital_Respiratory_Data__HRD__Metrics_by_Jurisdiction__National_Healthcare_Safety_Network__NHSN__20250220.csv"
]
trend_dfs = [pd.read_csv(folder_path + f, low_memory=False) for f in trend_files]
trend_df = pd.concat(trend_dfs, ignore_index=True)

# ✅ Save merged structured datasets
output_folder = "C:\\Users\\naing\\MultiVacSim\\data\\processed\\"

vaccination_df.to_csv(output_folder + "vaccination_data.csv", index=False)
hospitalization_df.to_csv(output_folder + "hospitalization_data.csv", index=False)
mortality_df.to_csv(output_folder + "mortality_data.csv", index=False)
trend_df.to_csv(output_folder + "trend_data.csv", index=False)

print("✅ Merged structured datasets saved successfully!")

✅ Merged structured datasets saved successfully!

In [10]:
import pandas as pd

# Load the merged datasets
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\processed\\"

vaccination_df = pd.read_csv(folder_path + "vaccination_data.csv", low_memory=False)
hospitalization_df = pd.read_csv(folder_path + "hospitalization_data.csv", low_memory=False)
mortality_df = pd.read_csv(folder_path + "mortality_data.csv", low_memory=False)
trend_df = pd.read_csv(folder_path + "trend_data.csv", low_memory=False)

# Check for the presence of "Flu", "Influenza", or "RSV" in column names or data
datasets = {
    "Vaccination Data": vaccination_df,
    "Hospitalization Data": hospitalization_df,
    "Mortality Data": mortality_df,
    "Trend Data": trend_df
}

for name, df in datasets.items():
    print(f"🔎 Checking {name} for Flu or RSV-related data...")

    # Check if any column mentions Flu, Influenza, or RSV
    flu_rsv_columns = [col for col in df.columns if any(keyword in col.lower() for keyword in ["flu", "influenza", "rsv"])]
    if flu_rsv_columns:
        print(f"   ✅ Flu or RSV-related columns found: {flu_rsv_columns}")
    else:
        print("   ❌ No Flu or RSV-related columns found.")

    # Check if Flu or RSV appears in any data values
    if df.astype(str).apply(lambda x: x.str.contains("Flu|Influenza|RSV", case=False, na=False)).any().any():
        print("   ✅ Flu or RSV-related data found in values.")
    else:
        print("   ❌ No Flu or RSV-related data found in values.")

    print("-" * 50)

🔎 Checking Vaccination Data for Flu or RSV-related data...
   ✅ Flu or RSV-related columns found: ['Location_and_Flu_Season_Order']
   ❌ No Flu or RSV-related data found in values.
--------------------------------------------------
🔎 Checking Hospitalization Data for Flu or RSV-related data...
   ✅ Flu or RSV-related columns found: ['Number of Adult Patients Hospitalized with Influenza', 'Number of Pedatric Patients Hospitalized with Influenza', 'Total Patients Hospitalized with Influenza', 'Number of Adult Patients Hospitalized with RSV', 'Number of Pediatric Patients Hospitalized with RSV', 'Total Patients Hospitalized with RSV', 'Number of Adult ICU Patients Hospitalized with Influenza', 'Number of Pediatric ICU Patients Hospitalized with Influenza', 'Total ICU Patients Hospitalized with Influenza', 'Number of Adult ICU Patients Hospitalized with RSV', 'Number of Pediatric ICU Patients Hospitalized with RSV', 'Total ICU Patients Hospitalized with RSV', 'Number of Pediatric Influenza Admissions, 0-4 years', 'Number of Pediatric Influenza Admissions, 5-17 years', 'Total Pediatric Influenza Admissions', 'Number of Adult Influenza Admissions, 18-49 years', 'Number of Adult Influenza Admissions, 50-64 years', 'Number of Adult Influenza Admissions, 65-74 years', 'Number of Adult Influenza Admissions, 75 plus years', 'Total Adult Influenza Admissions', 'Number of Influenza Admissions, unknown age', 'Total Influenza Admissions', 'Number of Pediatric RSV Admissions, 0-4 years', 'Number of Pediatric RSV Admissions, 5-17 years', 'Total Pediatric RSV Admissions', 'Number of Adult RSV Admissions, 18-49 years', 'Number of Adult RSV Admissions, 50-64 years', 'Number of Adult RSV Admissions, 65-74 years', 'Number of Adult RSV Admissions, 75 plus years', 'Total Adult RSV Admissions', 'Number of RSV Admissions, unknown age', 'Total RSV Admissions', 'Percent Inpatient Beds Occupied by Influenza Patients', 'Percent Inpatient Beds Occupied by RSV Patients', 'Percent ICU Beds Occupied by Influenza Patients', 'Percent ICU Beds Occupied by RSV Patients', 'Percent Adult Influenza Admissions', 'Percent Pediatric Influenza Admissions', 'Percent Adult RSV Admissions', 'Percent Pediatric RSV Admissions', 'Number Hospitals Reporting TotalPatients Hospitalized with Influenza', 'Number Hospitals Reporting Total Patients Hospitalized with RSV', 'Number Hospitals Reporting ICU Patients Hospitalized with Influenza', 'Number Hospitals Reporting ICU Patients Hospitalized with RSV', 'Number Hospitals Reporting Pediatric Influenza Admissions', 'Number Hospitals Reporting Adult Influenza Admissions', 'Number Hospitals Reporting Influenza Admissions', 'Number Hospitals Reporting Pediatric RSV Admissions', 'Number Hospitals Reporting Adult RSV Admissions', 'Number Hospitals Reporting RSV Admissions', 'Number Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients', 'Number Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients', 'Number Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients', 'Number Hospitals Reporting Percent ICU Beds Occupied by RSV Patients', 'Percent Hospitals Reporting TotalPatients Hospitalized with Influenza', 'Percent Hospitals Reporting Total Patients Hospitalized with RSV', 'Percent Hospitals Reporting ICU Patients Hospitalized with Influenza', 'Percent Hospitals Reporting ICU Patients Hospitalized with RSV', 'Percent Hospitals Reporting Pediatric Influenza Admissions', 'Percent Hospitals Reporting Adult Influenza Admissions', 'Percent Hospitals Reporting Influenza Admissions', 'Percent Hospitals Reporting Pediatric RSV Admissions', 'Percent Hospitals Reporting Adult RSV Admissions', 'Percent Hospitals Reporting RSV Admissions', 'Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients', 'Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients', 'Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients', 'Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients', 'Absolute Change in the Percent Hospitals Reporting TotalPatients Hospitalized with Influenza from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with RSV from Prior Week', 'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with Influenza from Prior Week', 'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with RSV from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Pediatric Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Adult Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting  Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Pediatric RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Adult RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients from Prior Week', 'Number of Pediatric Influenza Admissions, 0-4 years, per 100,000 population', 'Number of Pediatric Influenza Admissions, 5-17 years, per 100,000 population', 'Total Number of Pediatric Influenza Admissions per 100,000 population', 'Number of Adult Influenza Admissions, 18-49 years, per 100,000 population', 'Number of Adult Influenza Admissions, 50-64 years, per 100,000 population', 'Number of Adult Influenza Admissions, 65-74 years, per 100,000 population', 'Number of Adult Influenza Admissions, 75+ years, per 100,000 population', 'Total Number of Adult Influenza Admissions per 100,000 population', 'Total number of Influenza Admissions per 100,000 population', 'Number of Pediatric RSV Admissions, 0-4 years, per 100,000 population', 'Number of Pediatric RSV Admissions, 5-17 years, per 100,000 population', 'Total Number of Pediatric RSV Admissions per 100,000 population', 'Number of Adult RSV Admissions, 18-49 years, per 100,000 population', 'Number of Adult RSV Admissions, 50-64 years, per 100,000 population', 'Number of Adult RSV Admissions, 65-74 years, per 100,000 population', 'Number of Adult RSV Admissions, 75+ years, per 100,000 population', 'Total Number of Adult RSV Admissions per 100,000 population', 'Total number of RSV Admissions per 100,000 population', 'Percent Hospitals Reporting Total New Influenza Admissions Above 80%', 'Percent Hospitals Reporting Total New Influenza Admissions Above 90%', 'Percent Hospitals Reporting Total New RSV Admissions Above 80%', 'Percent Hospitals Reporting Total New RSV Admissions Above 90%']
   ✅ Flu or RSV-related data found in values.
--------------------------------------------------
🔎 Checking Mortality Data for Flu or RSV-related data...
   ❌ No Flu or RSV-related columns found.
   ❌ No Flu or RSV-related data found in values.
--------------------------------------------------
🔎 Checking Trend Data for Flu or RSV-related data...
   ✅ Flu or RSV-related columns found: ['Influenza_Season', 'Cumulative_Flu_Doses_Distributed', 'Number of Adult Patients Hospitalized with Influenza', 'Number of Pedatric Patients Hospitalized with Influenza', 'Total Patients Hospitalized with Influenza', 'Number of Adult Patients Hospitalized with RSV', 'Number of Pediatric Patients Hospitalized with RSV', 'Total Patients Hospitalized with RSV', 'Number of Adult ICU Patients Hospitalized with Influenza', 'Number of Pediatric ICU Patients Hospitalized with Influenza', 'Total ICU Patients Hospitalized with Influenza', 'Number of Adult ICU Patients Hospitalized with RSV', 'Number of Pediatric ICU Patients Hospitalized with RSV', 'Total ICU Patients Hospitalized with RSV', 'Number of Pediatric Influenza Admissions, 0-4 years', 'Number of Pediatric Influenza Admissions, 5-17 years', 'Total Pediatric Influenza Admissions', 'Number of Adult Influenza Admissions, 18-49 years', 'Number of Adult Influenza Admissions, 50-64 years', 'Number of Adult Influenza Admissions, 65-74 years', 'Number of Adult Influenza Admissions, 75 plus years', 'Total Adult Influenza Admissions', 'Number of Influenza Admissions, unknown age', 'Total Influenza Admissions', 'Number of Pediatric RSV Admissions, 0-4 years', 'Number of Pediatric RSV Admissions, 5-17 years', 'Total Pediatric RSV Admissions', 'Number of Adult RSV Admissions, 18-49 years', 'Number of Adult RSV Admissions, 50-64 years', 'Number of Adult RSV Admissions, 65-74 years', 'Number of Adult RSV Admissions, 75 plus years', 'Total Adult RSV Admissions', 'Number of RSV Admissions, unknown age', 'Total RSV Admissions', 'Percent Inpatient Beds Occupied by Influenza Patients', 'Percent Inpatient Beds Occupied by RSV Patients', 'Percent ICU Beds Occupied by Influenza Patients', 'Percent ICU Beds Occupied by RSV Patients', 'Percent Adult Influenza Admissions', 'Percent Pediatric Influenza Admissions', 'Percent Adult RSV Admissions', 'Percent Pediatric RSV Admissions', 'Number Hospitals Reporting TotalPatients Hospitalized with Influenza', 'Number Hospitals Reporting Total Patients Hospitalized with RSV', 'Number Hospitals Reporting ICU Patients Hospitalized with Influenza', 'Number Hospitals Reporting ICU Patients Hospitalized with RSV', 'Number Hospitals Reporting Pediatric Influenza Admissions', 'Number Hospitals Reporting Adult Influenza Admissions', 'Number Hospitals Reporting Influenza Admissions', 'Number Hospitals Reporting Pediatric RSV Admissions', 'Number Hospitals Reporting Adult RSV Admissions', 'Number Hospitals Reporting RSV Admissions', 'Number Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients', 'Number Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients', 'Number Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients', 'Number Hospitals Reporting Percent ICU Beds Occupied by RSV Patients', 'Percent Hospitals Reporting TotalPatients Hospitalized with Influenza', 'Percent Hospitals Reporting Total Patients Hospitalized with RSV', 'Percent Hospitals Reporting ICU Patients Hospitalized with Influenza', 'Percent Hospitals Reporting ICU Patients Hospitalized with RSV', 'Percent Hospitals Reporting Pediatric Influenza Admissions', 'Percent Hospitals Reporting Adult Influenza Admissions', 'Percent Hospitals Reporting Influenza Admissions', 'Percent Hospitals Reporting Pediatric RSV Admissions', 'Percent Hospitals Reporting Adult RSV Admissions', 'Percent Hospitals Reporting RSV Admissions', 'Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients', 'Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients', 'Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients', 'Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients', 'Absolute Change in the Percent Hospitals Reporting TotalPatients Hospitalized with Influenza from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with RSV from Prior Week', 'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with Influenza from Prior Week', 'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with RSV from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Pediatric Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Adult Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting  Influenza Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Pediatric RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Adult RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting RSV Admissions from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients from Prior Week', 'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients from Prior Week', 'Number of Pediatric Influenza Admissions, 0-4 years, per 100,000 population', 'Number of Pediatric Influenza Admissions, 5-17 years, per 100,000 population', 'Total Number of Pediatric Influenza Admissions per 100,000 population', 'Number of Adult Influenza Admissions, 18-49 years, per 100,000 population', 'Number of Adult Influenza Admissions, 50-64 years, per 100,000 population', 'Number of Adult Influenza Admissions, 65-74 years, per 100,000 population', 'Number of Adult Influenza Admissions, 75+ years, per 100,000 population', 'Total Number of Adult Influenza Admissions per 100,000 population', 'Total number of Influenza Admissions per 100,000 population', 'Number of Pediatric RSV Admissions, 0-4 years, per 100,000 population', 'Number of Pediatric RSV Admissions, 5-17 years, per 100,000 population', 'Total Number of Pediatric RSV Admissions per 100,000 population', 'Number of Adult RSV Admissions, 18-49 years, per 100,000 population', 'Number of Adult RSV Admissions, 50-64 years, per 100,000 population', 'Number of Adult RSV Admissions, 65-74 years, per 100,000 population', 'Number of Adult RSV Admissions, 75+ years, per 100,000 population', 'Total Number of Adult RSV Admissions per 100,000 population', 'Total number of RSV Admissions per 100,000 population', 'Percent Hospitals Reporting Total New Influenza Admissions Above 80%', 'Percent Hospitals Reporting Total New Influenza Admissions Above 90%', 'Percent Hospitals Reporting Total New RSV Admissions Above 80%', 'Percent Hospitals Reporting Total New RSV Admissions Above 90%']
   ❌ No Flu or RSV-related data found in values.
--------------------------------------------------

In [11]:
import os
import pandas as pd

# Define the folder path for processed datasets
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\processed\\"

# Load processed datasets
vaccination_df = pd.read_csv(folder_path + "vaccination_data.csv", low_memory=False)
hospitalization_df = pd.read_csv(folder_path + "hospitalization_data.csv", low_memory=False)
mortality_df = pd.read_csv(folder_path + "mortality_data.csv", low_memory=False)
trend_df = pd.read_csv(folder_path + "trend_data.csv", low_memory=False)

# Function to extract flu-related data
def extract_flu_data(df):
    return df[df.apply(lambda x: x.astype(str).str.contains("Flu|Influenza", case=False, na=False)).any(axis=1)]

# Function to remove flu-related data
def remove_flu_data(df):
    return df[~df.apply(lambda x: x.astype(str).str.contains("Flu|Influenza", case=False, na=False)).any(axis=1)]

# Extract and remove flu data from datasets
flu_vaccination_df = extract_flu_data(vaccination_df)
vaccination_df_cleaned = remove_flu_data(vaccination_df)

flu_hospitalization_df = extract_flu_data(hospitalization_df)
hospitalization_df_cleaned = remove_flu_data(hospitalization_df)

flu_trend_df = extract_flu_data(trend_df)
trend_df_cleaned = remove_flu_data(trend_df)

flu_mortality_df = extract_flu_data(mortality_df)
mortality_df_cleaned = remove_flu_data(mortality_df)

# Save flu-specific datasets
flu_vaccination_df.to_csv(folder_path + "flu_vaccination_data.csv", index=False)
flu_hospitalization_df.to_csv(folder_path + "flu_hospitalization_data.csv", index=False)
flu_trend_df.to_csv(folder_path + "flu_trend_data.csv", index=False)
flu_mortality_df.to_csv(folder_path + "flu_mortality_data.csv", index=False)

# Save cleaned COVID-19 datasets without flu data
vaccination_df_cleaned.to_csv(folder_path + "covid_vaccination_data.csv", index=False)
hospitalization_df_cleaned.to_csv(folder_path + "covid_hospitalization_data.csv", index=False)
trend_df_cleaned.to_csv(folder_path + "covid_trend_data.csv", index=False)
mortality_df_cleaned.to_csv(folder_path + "covid_mortality_data.csv", index=False)

# List of old files to delete
old_files = [
    "vaccination_data.csv",
    "hospitalization_data.csv",
    "mortality_data.csv",
    "trend_data.csv",
]

# Delete old files
for file in old_files:
    file_path = os.path.join(folder_path, file)
    if os.path.exists(file_path):
        os.remove(file_path)
        print(f"🗑️ Deleted: {file_path}")

# Confirm processing completion
print("✅ Flu-related data extracted and saved separately.")
print("✅ COVID-19-only datasets saved without flu-related data.")

🗑️ Deleted: C:\Users\naing\MultiVacSim\data\processed\vaccination_data.csv
🗑️ Deleted: C:\Users\naing\MultiVacSim\data\processed\hospitalization_data.csv
🗑️ Deleted: C:\Users\naing\MultiVacSim\data\processed\mortality_data.csv
🗑️ Deleted: C:\Users\naing\MultiVacSim\data\processed\trend_data.csv
✅ Flu-related data extracted and saved separately.
✅ COVID-19-only datasets saved without flu-related data.

In [12]:
import os

# Define folder path
folder_path = "C:\\Users\\naing\\MultiVacSim\\data\\processed\\"

# List all CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# Dictionary to store column mappings
column_mappings = {}

# Read each CSV and extract column names
for csv_file in csv_files:
    file_path = os.path.join(folder_path, csv_file)
    try:
        df = pd.read_csv(file_path, nrows=40)  # Read only first few rows to get columns
        column_mappings[csv_file] = list(df.columns)
    except Exception as e:
        column_mappings[csv_file] = f"Error reading file: {e}"

# Display extracted column mappings
# Convert to DataFrame and display
column_mappings_df = pd.DataFrame.from_dict(column_mappings, orient="index").T
column_mappings_df

,covid_hospitalization_data.csv,covid_mortality_data.csv,covid_trend_data.csv,covid_vaccination_data.csv,flu_hospitalization_data.csv,flu_mortality_data.csv,flu_trend_data.csv,flu_vaccination_data.csv
0,State,data_as_of,Vaccine,COVID-19_Season,State,data_as_of,Vaccine,COVID-19_Season
1,Season,data_period_end,Geographic Level,Week_ID,Season,data_period_end,Geographic Level,Week_ID
2,_WeekendDate,demographic,Geographic Name,Current_Season_Week_Ending_Label,_WeekendDate,demographic,Geographic Name,Current_Season_Week_Ending_Label
3,AgeCategory_Legend,population,Demographic_Level,MMWR_Week_Order,AgeCategory_Legend,population,Demographic_Level,MMWR_Week_Order
4,Sex_Label,covid_deaths,Demographic Name,MMWR_Year,Sex_Label,covid_deaths,Demographic Name,MMWR_Year
...,...,...,...,...,...,...,...,...
207,Cumulative Rate,None,Percent Hospitals Reporting Total New COVID-19...,None,Cumulative Rate,None,Percent Hospitals Reporting Total New COVID-19...,None
208,None,None,Percent Hospitals Reporting Total New Influenz...,None,None,None,Percent Hospitals Reporting Total New Influenz...,None
209,None,None,Percent Hospitals Reporting Total New Influenz...,None,None,None,Percent Hospitals Reporting Total New Influenz...,None
210,None,None,Percent Hospitals Reporting Total New RSV Admi...,None,None,None,Percent Hospitals Reporting Total New RSV Admi...,None
211,None,None,Percent Hospitals Reporting Total New RSV Admi...,None,None,None,Percent Hospitals Reporting Total New RSV Admi...,None

In [13]:
import pandas as pd

# Define uploaded file paths
file_paths = {
    "covid_vaccination_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_vaccination_data.csv",
    "covid_hospitalization_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_hospitalization_data.csv",
    "covid_mortality_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_mortality_data.csv",
    "covid_trend_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_trend_data.csv",
    "flu_vaccination_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_vaccination_data.csv",
    "flu_hospitalization_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_hospitalization_data.csv",
    "flu_mortality_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_mortality_data.csv",
    "flu_trend_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_trend_data.csv",
}


# Check column names in each dataset
column_info = {}
for name, path in file_paths.items():
    try:
        df = pd.read_csv(path, nrows=5)  # Load only first 5 rows for efficiency
        column_info[name] = df.columns.tolist()
    except Exception as e:
        column_info[name] = f"Error loading file: {e}"

# Display column names for verification
column_info

{'covid_vaccination_data': ['COVID-19_Season',
  'Week_ID',
  'Current_Season_Week_Ending_Label',
  'MMWR_Week_Order',
  'MMWR_Year',
  'MMWR_Week',
  'MMWR_Day',
  'Setting',
  'Doses',
  'Cumulative_Doses',
  'Location_and_Flu_Season_Order',
  'Current_Through',
  'Age_Group',
  'current_season',
  'Month',
  'Numerator',
  'Population',
  'Jurisdiction',
  'Estimate',
  'Age_group_label',
  'Legend',
  'Child or adult',
  'Week Ending',
  'Enrollment Date',
  'As of date',
  'Race and ethnicity',
  'comparison_type',
  'week_ending',
  'current_season_week_ending_label',
  'comparison_group_1',
  'comparison_group_2',
  'comparison_group1_point_estimate',
  'comparison_group2_point_estimate',
  'estimate_difference',
  'difference_estimate_lower_95_ci',
  'difference_estimate_upper_95_ci',
  'significant_at_95_pct',
  'comparison_group_1_sort_order',
  'comparison_group_2_sort_order'],
 'covid_hospitalization_data': ['State',
  'Season',
  '_WeekendDate',
  'AgeCategory_Legend',
  'Sex_Label',
  'Race_Label',
  'Type',
  'WeeklyRate',
  'CumulativeRate',
  'Week Ending Date',
  'Geographic aggregation',
  'Number of Inpatient Beds',
  'Number of Adult Inpatient Beds',
  'Number of Pediatric Inpatient beds',
  'Number of Inpatient Beds Occupied',
  'Number of Adult Inpatient Beds Occupied',
  'Number of Pediatric Inpatient Beds Occupied',
  'Number of ICU Beds',
  'Number of Adult ICU Beds',
  'Number of Pediatric ICU Beds',
  'Number of ICU Beds Occupied',
  'Number of Adult ICU Beds Occupied',
  'Number of Pediatric ICU Beds Occupied',
  'Number of Adult Patients Hospitalized with COVID-19',
  'Number of Pediatric Patients Hospitalized with COVID-19',
  'Total Patients Hospitalized with COVID-19',
  'Number of Adult Patients Hospitalized with Influenza',
  'Number of Pedatric Patients Hospitalized with Influenza',
  'Total Patients Hospitalized with Influenza',
  'Number of Adult Patients Hospitalized with RSV',
  'Number of Pediatric Patients Hospitalized with RSV',
  'Total Patients Hospitalized with RSV',
  'Number of Adult ICU Patients Hospitalized with COVID-19',
  'Number of Pediatric ICU Patients Hospitalized with COVID-19',
  'Total ICU Patients Hospitalized with COVID-19 ',
  'Number of Adult ICU Patients Hospitalized with Influenza',
  'Number of Pediatric ICU Patients Hospitalized with Influenza',
  'Total ICU Patients Hospitalized with Influenza',
  'Number of Adult ICU Patients Hospitalized with RSV',
  'Number of Pediatric ICU Patients Hospitalized with RSV',
  'Total ICU Patients Hospitalized with RSV',
  'Number of Pediatric COVID-19 Admissions, 0-4 years',
  'Number of Pediatric COVID-19 Admissions, 5-17 years',
  'Total Pediatric COVID-19 Admissions',
  'Number of Adult COVID-19 Admissions, 18-49 years',
  'Number of Adult COVID-19 Admissions, 50-64 years',
  'Number of Adult COVID-19 Admissions, 65-74 years',
  'Number of Adult COVID-19 Admissions, 75 plus',
  'Total Adult COVID-19 Admissions',
  'Number of COVID-19 Admissions, unknown age',
  'Total COVID-19 Admissions',
  'Number of Pediatric Influenza Admissions, 0-4 years',
  'Number of Pediatric Influenza Admissions, 5-17 years',
  'Total Pediatric Influenza Admissions',
  'Number of Adult Influenza Admissions, 18-49 years',
  'Number of Adult Influenza Admissions, 50-64 years',
  'Number of Adult Influenza Admissions, 65-74 years',
  'Number of Adult Influenza Admissions, 75 plus years',
  'Total Adult Influenza Admissions',
  'Number of Influenza Admissions, unknown age',
  'Total Influenza Admissions',
  'Number of Pediatric RSV Admissions, 0-4 years',
  'Number of Pediatric RSV Admissions, 5-17 years',
  'Total Pediatric RSV Admissions',
  'Number of Adult RSV Admissions, 18-49 years',
  'Number of Adult RSV Admissions, 50-64 years',
  'Number of Adult RSV Admissions, 65-74 years',
  'Number of Adult RSV Admissions, 75 plus years',
  'Total Adult RSV Admissions',
  'Number of RSV Admissions, unknown age',
  'Total RSV Admissions',
  'Percent Inpatient Beds Occupied',
  'Percent Inpatient Beds Occupied by COVID-19 Patients',
  'Percent Inpatient Beds Occupied by Influenza Patients',
  'Percent Inpatient Beds Occupied by RSV Patients',
  'Percent ICU Beds Occupied',
  'Percent ICU Beds Occupied by COVID-19 Patients',
  'Percent ICU Beds Occupied by Influenza Patients',
  'Percent ICU Beds Occupied by RSV Patients',
  'Percent Adult COVID-19 Admissions',
  'Percent Pediatric COVID-19 Admissions',
  'Percent Adult Influenza Admissions',
  'Percent Pediatric Influenza Admissions',
  'Percent Adult RSV Admissions',
  'Percent Pediatric RSV Admissions',
  'Number Hospitals Reporting Number of Inpatient Beds',
  'Number Hospitals Reporting Number of Inpatient Beds Occupied',
  'Number Hospitals Reporting Number of ICU Beds ',
  'Number Hospitals Reporting Number of ICU Beds Occupied',
  'Number Hospitals Reporting Total Patients Hospitalized with COVID-19',
  'Number Hospitals Reporting TotalPatients Hospitalized with Influenza',
  'Number Hospitals Reporting Total Patients Hospitalized with RSV',
  'Number Hospitals Reporting ICU Patients Hospitalized with COVID-19 ',
  'Number Hospitals Reporting ICU Patients Hospitalized with Influenza',
  'Number Hospitals Reporting ICU Patients Hospitalized with RSV',
  'Number Hospitals Reporting Pediatric COVID-19 Admissions',
  'Number Hospitals Reporting Adult COVID-19 Admissions',
  'Number Hospitals Reporting COVID-19 Admissions',
  'Number Hospitals Reporting Pediatric Influenza Admissions',
  'Number Hospitals Reporting Adult Influenza Admissions',
  'Number Hospitals Reporting Influenza Admissions',
  'Number Hospitals Reporting Pediatric RSV Admissions',
  'Number Hospitals Reporting Adult RSV Admissions',
  'Number Hospitals Reporting RSV Admissions',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied',
  'Number Hospitals Reporting Percent ICU Beds Occupied',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by RSV Patients',
  'Percent Hospitals Reporting Number of Inpatient Beds',
  'Percent Hospitals Reporting Number of Inpatient Beds Occupied',
  'Percent Hospitals Reporting Number of ICU Beds ',
  'Percent Hospitals Reporting Number of ICU Beds Occupied',
  'Percent Hospitals Reporting Total Patients Hospitalized with COVID-19',
  'Percent Hospitals Reporting TotalPatients Hospitalized with Influenza',
  'Percent Hospitals Reporting Total Patients Hospitalized with RSV',
  'Percent Hospitals Reporting ICU Patients Hospitalized with COVID-19 ',
  'Percent Hospitals Reporting ICU Patients Hospitalized with Influenza',
  'Percent Hospitals Reporting ICU Patients Hospitalized with RSV',
  'Percent Hospitals Reporting Pediatric COVID-19 Admissions',
  'Percent Hospitals Reporting Adult COVID-19 Admissions',
  'Percent Hospitals Reporting COVID-19 Admissions',
  'Percent Hospitals Reporting Pediatric Influenza Admissions',
  'Percent Hospitals Reporting Adult Influenza Admissions',
  'Percent Hospitals Reporting Influenza Admissions',
  'Percent Hospitals Reporting Pediatric RSV Admissions',
  'Percent Hospitals Reporting Adult RSV Admissions',
  'Percent Hospitals Reporting RSV Admissions',
  'Percent Hospitals Reporting Percent Inpatient Beds Occupied',
  'Percent Hospitals Reporting Percent ICU Beds Occupied',
  'Percent Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients',
  'Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients',
  'Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients',
  'Percent Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients',
  'Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients',
  'Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients',
  'Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds from Prior Week',
  'Absolute Change in the Absolute Change in the Percent Hospitals Reporting Number of Inpatient Beds Occupied from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Number of ICU Beds from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Number of ICU Beds Occupied from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with COVID-19 from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting TotalPatients Hospitalized with Influenza from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Total Patients Hospitalized with RSV from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with COVID-19 from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with Influenza from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting ICU Patients Hospitalized with RSV from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Pediatric COVID-19 Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Adult COVID-19 Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting COVID-19 Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Pediatric Influenza Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Adult Influenza Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting  Influenza Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Pediatric RSV Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Adult RSV Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting RSV Admissions from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients from Prior Week',
  'Absolute Change in the Percent Hospitals Reporting Percent ICU Beds Occupied by RSV Patients from Prior Week',
  'Number of Pediatric COVID-19 Admissions, 0-4 years, per 100,000 population',
  'Number of Pediatric COVID-19 Admissions, 5-17 years, per 100,000 population',
  'Total Number of Pediatric COVID-19 Admissions per 100,000 population',
  'Number of Adult COVID-19 Admissions, 18-49 years, per 100,000 population',
  'Number of Adult COVID-19 Admissions, 50-64 years, per 100,000 population',
  'Number of Adult COVID-19 Admissions, 65-74 years, per 100,000 population',
  'Number of Adult COVID-19 Admissions, 75+ years, per 100,000 population',
  'Total Number of Adult COVID-19 Admissions per 100,000 population',
  'Total number of COVID-19 Admissions per 100,000 population',
  'Number of Pediatric Influenza Admissions, 0-4 years, per 100,000 population',
  'Number of Pediatric Influenza Admissions, 5-17 years, per 100,000 population',
  'Total Number of Pediatric Influenza Admissions per 100,000 population',
  'Number of Adult Influenza Admissions, 18-49 years, per 100,000 population',
  'Number of Adult Influenza Admissions, 50-64 years, per 100,000 population',
  'Number of Adult Influenza Admissions, 65-74 years, per 100,000 population',
  'Number of Adult Influenza Admissions, 75+ years, per 100,000 population',
  'Total Number of Adult Influenza Admissions per 100,000 population',
  'Total number of Influenza Admissions per 100,000 population',
  'Number of Pediatric RSV Admissions, 0-4 years, per 100,000 population',
  'Number of Pediatric RSV Admissions, 5-17 years, per 100,000 population',
  'Total Number of Pediatric RSV Admissions per 100,000 population',
  'Number of Adult RSV Admissions, 18-49 years, per 100,000 population',
  'Number of Adult RSV Admissions, 50-64 years, per 100,000 population',
  'Number of Adult RSV Admissions, 65-74 years, per 100,000 population',
  'Number of Adult RSV Admissions, 75+ years, per 100,000 population',
  'Total Number of Adult RSV Admissions per 100,000 population',
  'Total number of RSV Admissions per 100,000 population',
  'Percent Hospitals Reporting Total New COVID-19 Admissions Above 80%',
  'Percent Hospitals Reporting Total New COVID-19 Admissions Above 90%',
  'Percent Hospitals Reporting Total New Influenza Admissions Above 80%',
  'Percent Hospitals Reporting Total New Influenza Admissions Above 90%',
  'Percent Hospitals Reporting Total New RSV Admissions Above 80%',
  'Percent Hospitals Reporting Total New RSV Admissions Above 90%',
  'Surveillance Network',
  'MMWR Year',
  'MMWR Week',
  'Age group',
  'Sex',
  'Race/Ethnicity',
  'Site',
  'Weekly Rate',
  'Cumulative Rate'],
 'covid_mortality_data': ['data_as_of',
  'data_period_end',
  'demographic',
  'population',
  'covid_deaths',
  'total_deaths',
  'pop_percent',
  'jurisdiction_residence',
  'data_period_start',
  'group',
  'subgroup1',
  'subgroup2',
  'crude_rate',
  'conf_int_95pct_lower_crude',
  'conf_int_95pct_upper_crude',
  'note'],
 'covid_trend_data': ['Vaccine',
  'Geographic Level',
  'Geographic Name',
  'Demographic_Level',
  'Demographic Name',
  'Indicator_label',
  'Indicator_category_label',
  'Month_Week',
  'Week_ending',
  'Estimate',
  'CI_Half_width_95pct',
  'Unweighted Sample Size',
  'suppression_flag',
  'Influenza_Season',
  'Start_Date',
  'End_Date',
  'Reporting_TimeFrame',
  'Week_Ending_Date',
  'Week_Sort_Order',
  'Current_Season_Week_Ending_Label',
  'Cumulative_Flu_Doses_Distributed',
  'Current_Through',
  'Week Ending Date',
  'Geographic aggregation',
  'Number of Inpatient Beds',
  'Number of Adult Inpatient Beds',
  'Number of Pediatric Inpatient beds',
  'Number of Inpatient Beds Occupied',
  'Number of Adult Inpatient Beds Occupied',
  'Number of Pediatric Inpatient Beds Occupied',
  'Number of ICU Beds',
  'Number of Adult ICU Beds',
  'Number of Pediatric ICU Beds',
  'Number of ICU Beds Occupied',
  'Number of Adult ICU Beds Occupied',
  'Number of Pediatric ICU Beds Occupied',
  'Number of Adult Patients Hospitalized with COVID-19',
  'Number of Pediatric Patients Hospitalized with COVID-19',
  'Total Patients Hospitalized with COVID-19',
  'Number of Adult Patients Hospitalized with Influenza',
  'Number of Pedatric Patients Hospitalized with Influenza',
  'Total Patients Hospitalized with Influenza',
  'Number of Adult Patients Hospitalized with RSV',
  'Number of Pediatric Patients Hospitalized with RSV',
  'Total Patients Hospitalized with RSV',
  'Number of Adult ICU Patients Hospitalized with COVID-19',
  'Number of Pediatric ICU Patients Hospitalized with COVID-19',
  'Total ICU Patients Hospitalized with COVID-19 ',
  'Number of Adult ICU Patients Hospitalized with Influenza',
  'Number of Pediatric ICU Patients Hospitalized with Influenza',
  'Total ICU Patients Hospitalized with Influenza',
  'Number of Adult ICU Patients Hospitalized with RSV',
  'Number of Pediatric ICU Patients Hospitalized with RSV',
  'Total ICU Patients Hospitalized with RSV',
  'Number of Pediatric COVID-19 Admissions, 0-4 years',
  'Number of Pediatric COVID-19 Admissions, 5-17 years',
  'Total Pediatric COVID-19 Admissions',
  'Number of Adult COVID-19 Admissions, 18-49 years',
  'Number of Adult COVID-19 Admissions, 50-64 years',
  'Number of Adult COVID-19 Admissions, 65-74 years',
  'Number of Adult COVID-19 Admissions, 75 plus',
  'Total Adult COVID-19 Admissions',
  'Number of COVID-19 Admissions, unknown age',
  'Total COVID-19 Admissions',
  'Number of Pediatric Influenza Admissions, 0-4 years',
  'Number of Pediatric Influenza Admissions, 5-17 years',
  'Total Pediatric Influenza Admissions',
  'Number of Adult Influenza Admissions, 18-49 years',
  'Number of Adult Influenza Admissions, 50-64 years',
  'Number of Adult Influenza Admissions, 65-74 years',
  'Number of Adult Influenza Admissions, 75 plus years',
  'Total Adult Influenza Admissions',
  'Number of Influenza Admissions, unknown age',
  'Total Influenza Admissions',
  'Number of Pediatric RSV Admissions, 0-4 years',
  'Number of Pediatric RSV Admissions, 5-17 years',
  'Total Pediatric RSV Admissions',
  'Number of Adult RSV Admissions, 18-49 years',
  'Number of Adult RSV Admissions, 50-64 years',
  'Number of Adult RSV Admissions, 65-74 years',
  'Number of Adult RSV Admissions, 75 plus years',
  'Total Adult RSV Admissions',
  'Number of RSV Admissions, unknown age',
  'Total RSV Admissions',
  'Percent Inpatient Beds Occupied',
  'Percent Inpatient Beds Occupied by COVID-19 Patients',
  'Percent Inpatient Beds Occupied by Influenza Patients',
  'Percent Inpatient Beds Occupied by RSV Patients',
  'Percent ICU Beds Occupied',
  'Percent ICU Beds Occupied by COVID-19 Patients',
  'Percent ICU Beds Occupied by Influenza Patients',
  'Percent ICU Beds Occupied by RSV Patients',
  'Percent Adult COVID-19 Admissions',
  'Percent Pediatric COVID-19 Admissions',
  'Percent Adult Influenza Admissions',
  'Percent Pediatric Influenza Admissions',
  'Percent Adult RSV Admissions',
  'Percent Pediatric RSV Admissions',
  'Number Hospitals Reporting Number of Inpatient Beds',
  'Number Hospitals Reporting Number of Inpatient Beds Occupied',
  'Number Hospitals Reporting Number of ICU Beds ',
  'Number Hospitals Reporting Number of ICU Beds Occupied',
  'Number Hospitals Reporting Total Patients Hospitalized with COVID-19',
  'Number Hospitals Reporting TotalPatients Hospitalized with Influenza',
  'Number Hospitals Reporting Total Patients Hospitalized with RSV',
  'Number Hospitals Reporting ICU Patients Hospitalized with COVID-19 ',
  'Number Hospitals Reporting ICU Patients Hospitalized with Influenza',
  'Number Hospitals Reporting ICU Patients Hospitalized with RSV',
  'Number Hospitals Reporting Pediatric COVID-19 Admissions',
  'Number Hospitals Reporting Adult COVID-19 Admissions',
  'Number Hospitals Reporting COVID-19 Admissions',
  'Number Hospitals Reporting Pediatric Influenza Admissions',
  'Number Hospitals Reporting Adult Influenza Admissions',
  'Number Hospitals Reporting Influenza Admissions',
  'Number Hospitals Reporting Pediatric RSV Admissions',
  'Number Hospitals Reporting Adult RSV Admissions',
  'Number Hospitals Reporting RSV Admissions',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied',
  'Number Hospitals Reporting Percent ICU Beds Occupied',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by COVID-19 Patients',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by Influenza Patients',
  'Number Hospitals Reporting Percent Inpatient Beds Occupied by RSV Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by COVID-19 Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by Influenza Patients',
  'Number Hospitals Reporting Percent ICU Beds Occupied by RSV Patients',
  'Percent Hospitals Reporting Number of Inpatient Beds',
  'Percent Hospitals Reporting Number of Inpatient Beds Occupied',
  'Percent Hospitals Reporting Number of ICU Beds ',

In [14]:
import numpy as np 
import pandas as pd
import dask.dataframe as dd

def standardize_location_column(df):
    for col in df.columns:
        if col.lower() in ["state", "jurisdiction", "jurisdiction_residence", "geographic name"]:
            df = df.rename(columns={col: "state"})
    
    # Ensure state column is always of type string
    if "state" in df.columns:
        df["state"] = df["state"].astype(str)
    
    return df


# Define file paths
file_paths = {
    "covid_vaccination_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_vaccination_data.csv",
    "covid_hospitalization_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_hospitalization_data.csv",
    "covid_mortality_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_mortality_data.csv",
    "covid_trend_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\covid_trend_data.csv",
    "flu_vaccination_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_vaccination_data.csv",
    "flu_hospitalization_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_hospitalization_data.csv",
    "flu_mortality_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_mortality_data.csv",
    "flu_trend_data": "C:\\Users\\naing\\MultiVacSim\\data\\processed\\flu_trend_data.csv",
}

updated_column_mappings = { 
    "covid_vaccination_data": {
        "COVID-19_Season": "season",
        "Week_ID": "week_id",
        "Current_Season_Week_Ending_Label": "week_ending",
        "MMWR_Week_Order": "mmwr_week_order",
        "MMWR_Year": "mmwr_year",
        "Jurisdiction": "state",
    },
    "covid_hospitalization_data": {
        "State": "state",
        "Season": "season",
        "_WeekendDate": "weekend_date",
        "Cumulative Rate": "hospitalization_rate",
    },
    "covid_mortality_data": {
        "data_as_of": "data_date",
        "data_period_end": "data_period_end",
        "demographic": "demographic",
        "population": "population",
        "covid_deaths": "death_rate",
        "jurisdiction_residence": "state",
    },
    "covid_trend_data": {
        "Vaccine": "vaccine",
        "Geographic Level": "geographic_level",
        "Geographic Name": "state",
        "Percent Hospitals Reporting Total New COVID-19 Admissions": "emergency_visits",
    },
    "flu_vaccination_data": {
        "COVID-19_Season": "season",
        "Week_ID": "week_id",
        "Current_Season_Week_Ending_Label": "week_ending",
        "MMWR_Week_Order": "mmwr_week_order",
        "MMWR_Year": "mmwr_year",
        "Jurisdiction": "state",
    },
    "flu_hospitalization_data": {
        "State": "state",
        "Season": "season",
        "_WeekendDate": "weekend_date",
        "Cumulative Rate": "flu_hospitalization_rate",
    },
    "flu_mortality_data": {
        "data_as_of": "data_date",
        "data_period_end": "data_period_end",
        "demographic": "demographic",
        "population": "population",
        "covid_deaths": "flu_death_rate",
        "jurisdiction_residence": "state",
    },
    "flu_trend_data": {
        "Vaccine": "vaccine",
        "Geographic Level": "geographic_level",
        "Geographic Name": "state",
        "Percent Hospitals Reporting Total New Influenza Admissions": "flu_emergency_visits",
    }
}

# Apply standardization to each dataset
standardized_datasets = {}
for name, mappings in updated_column_mappings.items():
    try:
        # Explicitly define dtype to avoid float/string mismatch
        df = dd.read_csv(file_paths[name], 
                         usecols=[col for col in mappings.keys() if col in pd.read_csv(file_paths[name], nrows=1).columns], 
                         engine="python",
                         dtype={'Jurisdiction': 'object', 'State': 'object', 
                                'jurisdiction_residence': 'object', 'Geographic Name': 'object'}
                        )

        # Rename columns based on mapping
        df = df.rename(columns=mappings)

        # Standardize the 'state' column
        df = standardize_location_column(df)

        # Ensure 'state' column is always a string
        if "state" in df.columns:
            df["state"] = df["state"].astype(str)

        # Store in dataset dictionary
        standardized_datasets[name] = df

        print(f"✅ Successfully standardized: {name}")

    except Exception as e:
        print(f"❌ Error processing {name}: {e}")
        
# Display standardized column names for verification
standardized_columns = {name: list(df.columns) for name, df in standardized_datasets.items()}
pd.DataFrame.from_dict(standardized_columns, orient="index").T

✅ Successfully standardized: covid_vaccination_data
✅ Successfully standardized: covid_hospitalization_data
✅ Successfully standardized: covid_mortality_data
✅ Successfully standardized: covid_trend_data
✅ Successfully standardized: flu_vaccination_data
✅ Successfully standardized: flu_hospitalization_data
✅ Successfully standardized: flu_mortality_data
✅ Successfully standardized: flu_trend_data

,covid_vaccination_data,covid_hospitalization_data,covid_mortality_data,covid_trend_data,flu_vaccination_data,flu_hospitalization_data,flu_mortality_data,flu_trend_data
0,season,state,data_date,vaccine,season,state,data_date,vaccine
1,week_id,season,data_period_end,geographic_level,week_id,season,data_period_end,geographic_level
2,week_ending,weekend_date,demographic,state,week_ending,weekend_date,demographic,state
3,mmwr_week_order,hospitalization_rate,population,None,mmwr_week_order,flu_hospitalization_rate,population,None
4,mmwr_year,None,death_rate,None,mmwr_year,None,flu_death_rate,None
5,state,None,state,None,state,None,state,None

In [15]:
for name, df in standardized_datasets.items():
    if "state" not in df.columns:
        print(f"❌ Missing 'state' column in {name}")
    else:
        print(f"✅ 'state' column exists in {name}")

✅ 'state' column exists in covid_vaccination_data
✅ 'state' column exists in covid_hospitalization_data
✅ 'state' column exists in covid_mortality_data
✅ 'state' column exists in covid_trend_data
✅ 'state' column exists in flu_vaccination_data
✅ 'state' column exists in flu_hospitalization_data
✅ 'state' column exists in flu_mortality_data
✅ 'state' column exists in flu_trend_data

In [16]:
for name, df in standardized_datasets.items():
    print(f"{name} columns: {df.columns.tolist()}")

covid_vaccination_data columns: ['season', 'week_id', 'week_ending', 'mmwr_week_order', 'mmwr_year', 'state']
covid_hospitalization_data columns: ['state', 'season', 'weekend_date', 'hospitalization_rate']
covid_mortality_data columns: ['data_date', 'data_period_end', 'demographic', 'population', 'death_rate', 'state']
covid_trend_data columns: ['vaccine', 'geographic_level', 'state']
flu_vaccination_data columns: ['season', 'week_id', 'week_ending', 'mmwr_week_order', 'mmwr_year', 'state']
flu_hospitalization_data columns: ['state', 'season', 'weekend_date', 'flu_hospitalization_rate']
flu_mortality_data columns: ['data_date', 'data_period_end', 'demographic', 'population', 'flu_death_rate', 'state']
flu_trend_data columns: ['vaccine', 'geographic_level', 'state']

# Multi-Scale Data Structuring

In [17]:
# # 📌 Step 1: Aggregate National-Level Data
# def aggregate_national(df, columns):
#     return df[columns].mean().compute()

# national_data = {
#     "covid_hospitalization_rate": aggregate_national(standardized_datasets["covid_hospitalization_data"], ["hospitalization_rate"]),
#     "covid_death_rate": aggregate_national(standardized_datasets["covid_mortality_data"], ["death_rate"]),
#     "flu_hospitalization_rate": aggregate_national(standardized_datasets["flu_hospitalization_data"], ["flu_hospitalization_rate"]),
#     "flu_death_rate": aggregate_national(standardized_datasets["flu_mortality_data"], ["flu_death_rate"]),
# }

# # 📌 Step 2: Aggregate Regional Data (HHS Regions or Census Divisions)
# def aggregate_regional(df, columns, group_by="hhs_region"):
#     return df.groupby(group_by)[columns].mean().compute()

# regional_data = {
#     "covid_hospitalization_rate": aggregate_regional(standardized_datasets["covid_hospitalization_data"], ["hospitalization_rate"]),
#     "covid_death_rate": aggregate_regional(standardized_datasets["covid_mortality_data"], ["death_rate"]),
#     "flu_hospitalization_rate": aggregate_regional(standardized_datasets["flu_hospitalization_data"], ["flu_hospitalization_rate"]),
#     "flu_death_rate": aggregate_regional(standardized_datasets["flu_mortality_data"], ["flu_death_rate"]),
# }

# # 📌 Step 3: Use State-Level Data for Final Vaccine Allocation
# state_data = {
#     "covid_vaccination": standardized_datasets["covid_vaccination_data"].compute(),
#     "covid_hospitalization": standardized_datasets["covid_hospitalization_data"].compute(),
#     "covid_mortality": standardized_datasets["covid_mortality_data"].compute(),
#     "covid_trend": standardized_datasets["covid_trend_data"].compute(),
#     "flu_vaccination": standardized_datasets["flu_vaccination_data"].compute(),
#     "flu_hospitalization": standardized_datasets["flu_hospitalization_data"].compute(),
#     "flu_mortality": standardized_datasets["flu_mortality_data"].compute(),
#     "flu_trend": standardized_datasets["flu_trend_data"].compute(),
# }

# # 📌 Save structured datasets
# pd.DataFrame(national_data, index=[0]).to_csv(folder_path + "national_vaccine_data.csv", index=False)
# pd.DataFrame(regional_data).to_csv(folder_path + "regional_vaccine_data.csv", index=False)

# for key, df in state_data.items():
#     df.to_csv(folder_path + f"{key}_structured.csv", index=False)

# print("✅ Multi-Scale Vaccine Data Structuring Completed!")

# Synthetic Data Creation

In [34]:
import numpy as np
import pandas as pd
import dask.dataframe as dd

# Function to process each partition separately
def process_partition(covid_partition, flu_partition):
    """Process each Dask partition separately to avoid memory overload."""
    if covid_partition.empty or flu_partition.empty:
        return pd.DataFrame()  # Return empty DataFrame to maintain structure

    synthetic_data = {
        "state": covid_partition["state"].astype(str),  # Ensure consistent datatype
        "population_size": np.random.randint(500000, 5000000, size=min(len(covid_partition), 1000)),
        
        # 🏥 Hospitalization & Death Rates
        "hospitalization_rate": covid_partition["hospitalization_rate"].fillna(0.01),  # COVID-19
        "flu_hospitalization_rate": flu_partition["flu_hospitalization_rate"].fillna(0.01),  # Flu
        "death_rate": covid_partition["death_rate"].fillna(0.001),  # COVID-19
        "flu_death_rate": flu_partition["flu_death_rate"].fillna(0.001),  # Flu

        # 💉 Vaccine Coverage
        "vaccine_coverage": covid_partition["vaccine_coverage"].fillna(0.0),  # COVID-19
        "flu_vaccine_coverage": flu_partition["vaccine_coverage"].fillna(0.0),  # Flu

        # 🔄 Booster Coverage & Hesitancy
        "booster_coverage": covid_partition["booster_coverage"].fillna(0.0),  
        "vaccine_hesitancy": np.random.uniform(0.1, 0.4, len(covid_partition)),
        "booster_demand": np.random.uniform(0.1, 0.5, len(covid_partition)),

        # 🔬 COVID Variant Severity
        "variant_severity": np.random.randint(1, 5, len(covid_partition)),

        # 🌍 Seasonal Impact Using Flu Hospitalization Rate
        "seasonality_factor": flu_partition["flu_hospitalization_rate"].fillna(0.05),

        # 🚑 Emergency Visits (COVID & Flu)
        "emergency_visits": covid_partition["emergency_visits"].fillna(0),
        "flu_emergency_visits": flu_partition["flu_emergency_visits"].fillna(0)
    }
    
    return pd.DataFrame(synthetic_data)

# Function to create and save synthetic population data
def create_synthetic_population_data(covid_vaccine, covid_hosp, covid_mort, covid_trend, 
                                     flu_vaccine, flu_hosp, flu_mort, flu_trend, output_file):
    """Creates a synthetic population dataset by combining vaccine allocation factors."""

    # Ensure "state" is string to prevent merge issues
    for df in [covid_vaccine, covid_hosp, covid_mort, covid_trend, flu_vaccine, flu_hosp, flu_mort, flu_trend]:
        df["state"] = df["state"].astype(str)

    # Define common columns for merging
    common_columns = ["state"]
    if "date" in covid_vaccine.columns:
        common_columns.append("date")

    # Merge only necessary columns using Dask (lazy execution)
    covid_data = covid_vaccine.merge(covid_hosp, on=common_columns, how="left") \
                              .merge(covid_mort, on=common_columns, how="left") \
                              .merge(covid_trend, on=common_columns, how="left")

    flu_data = flu_vaccine.merge(flu_hosp, on=common_columns, how="left") \
                          .merge(flu_mort, on=common_columns, how="left") \
                          .merge(flu_trend, on=common_columns, how="left")
    def partition_size(df):
        return pd.DataFrame({"num_rows": [len(df)]})  # Count rows in each partition

    def partition_memory(df):
        return pd.DataFrame({"memory_usage_MB": [df.memory_usage(deep=True).sum() / (1024 * 1024)]})

    print(f"COVID Data Partitions: {covid_data.npartitions}")
    print(f"Flu Data Partitions: {flu_data.npartitions}")
    # Compute partition sizes
    
    partition_sizes = covid_data.map_partitions(partition_size).compute()
    print(partition_sizes)

    partition_memory_usage = covid_data.map_partitions(partition_memory).compute()
    print(partition_memory_usage)

    # covid_data = covid_data.repartition(npartitions=flu_data.npartitions)
    
    # Target partition size (e.g., 100 MB per partition)
    target_size_mb = 100
    avg_partition_size = partition_memory_usage["memory_usage_MB"].mean()

    # Calculate optimal partitions
    optimal_partitions = max(1, int((covid_data.memory_usage(deep=True).sum() / (1024 * 1024)) / target_size_mb))
    print(f"Optimal partitions: {optimal_partitions}")

    # Repartition
    # covid_data = covid_data.repartition(npartitions=optimal_partitions)

    # Use Dask’s map_partitions to process each partition separately
    # synthetic_population_df = covid_data.map_partitions(
    #     process_partition, flu_data,
    #     meta=pd.DataFrame(columns=[
    #         "state", "population_size", "hospitalization_rate", "flu_hospitalization_rate",
    #         "death_rate", "flu_death_rate", "vaccine_coverage", "flu_vaccine_coverage",
    #         "booster_coverage", "vaccine_hesitancy", "booster_demand", "variant_severity",
    #         "seasonality_factor", "emergency_visits", "flu_emergency_visits"
    #     ])
    # )

    # Save to Parquet in partitions to reduce memory usage
    # synthetic_population_df.to_parquet(output_file, engine="pyarrow", write_index=False, overwrite=True)

    # print(f"✅ Synthetic Population Data Saved: {output_file}")


# Filepath for output
# output_file = "C:\\Users\\naing\\MultiVacSim\\data\\processed\\synthetic_population_data.parquet"

# Generate synthetic dataset with trend data and save efficiently
# create_synthetic_population_data(
#     standardized_datasets["covid_vaccination_data"], standardized_datasets["covid_hospitalization_data"], 
#     standardized_datasets["covid_mortality_data"], standardized_datasets["covid_trend_data"],
#     standardized_datasets["flu_vaccination_data"], standardized_datasets["flu_hospitalization_data"], 
#     standardized_datasets["flu_mortality_data"], standardized_datasets["flu_trend_data"],
#     output_file
# )